version: "2"

services:
    server:
        build: .
        container_name: server
        environment:
            - NODE_ENV=development
            - PORT=5555
            - REDIS_URL=redis://my-cache
        command: "sh -c 'npm i && npm run dev'"
        volumes:
            - .:/var/www/app
        links:
            - redis
        ports:
            - "5555:5555"

    worker:
        build: .
        container_name: worker
        environment:
            - NODE_ENV=development
            - PORT=3000
            - REDIS_URL=redis://my-cache
        command: "sh -c 'npm i && npm run worker:dev'"
        volumes:
            - .:/var/www/app
        links:
            - redis

    redis:
        image: redis
        container_name: redis-cache
        expose:
            - "6379"